/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Singleton;

import Decorador.Cafe;
import Decorador.Cafe_Solo;
import Decorador.Cajeta;
import Decorador.Oreo;
import Decorador.Panna;
import Estrategia.Efectivo;
import Estrategia.Tarjetas;
import Iterador.IteraLista;
import Iterador.IteraPrecio;
import Iterador.IteraTipo;
import Iterador.Lista_Cafes;
import Observador.GranHermano;
import Observador.Observador;
import Observador.Sujeto;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import proyecto_cafe.Main;
import proyecto_cafe.Main;

/**
 *
 * @author Eli
 */
public class SingletonContruyeCafe extends javax.swing.JInternalFrame implements Sujeto {

    Lista_Cafes ls;
    IteraLista it;
    IteraPrecio itp;
    IteraTipo itt;
    Cafe_Solo capuccino;
    Cafe_Solo americano;
    Cafe_Solo express;
    Cafe_Solo moka;
    Cafe_Solo capuccino_frio;
    Cafe_Solo moka_frio;
    Cafe_Solo base;
    private static int numIns = 0;
    private static SingletonContruyeCafe instancia;
    private float total_pagar;
    private float costo_unidad, costo_decorado;
    private String nombre_base;
    private boolean cajeta, oreo, panna;
    private ArrayList observadores;
    String ingredientes;

    protected SingletonContruyeCafe() {
        numIns++;
        total_pagar = 0;
        cajeta = false;
        oreo = false;
        panna = false;
        observadores = new ArrayList();
        initComponents();

        iniciar('C');
    }

    public static SingletonContruyeCafe getInstancia() {
        if (instancia == null) {
            instancia = new SingletonContruyeCafe();
            instancia.setVisible(true);
            etiNumIns.setText(instancia.getNumIns() + "  " + System.currentTimeMillis());
            GranHermano gran_her = new GranHermano(SingletonContruyeCafe.instancia);
        }
        numIns = 0;
        return instancia;

    }

    public int getNumIns() {
        return numIns;
    }

    public void iniciar(char tipo) {
        ls = new Lista_Cafes();
        itt = new IteraTipo(ls, tipo);

        capuccino = new Cafe_Solo('C', "Capuccino", 25);
        americano = new Cafe_Solo('C', "Americano", 23);
        express = new Cafe_Solo('C', "Express", 20);
        moka = new Cafe_Solo('C', "Moka", 21);
        capuccino_frio = new Cafe_Solo('F', "Capuccino Frio", 30);
        moka_frio = new Cafe_Solo('F', "Moka Frio", 35);

        ls.add(capuccino);
        ls.add(americano);
        ls.add(express);
        ls.add(moka);
        ls.add(capuccino_frio);
        ls.add(moka_frio);

        combo(ls.modelo_combo(itt));
    }

    public void reinicia(char tipo) {
        ls = new Lista_Cafes();
        itt = new IteraTipo(ls, tipo);

        capuccino = new Cafe_Solo('C', "Capuccino", 25);
        americano = new Cafe_Solo('C', "Americano", 23);
        express = new Cafe_Solo('C', "Express", 20);
        moka = new Cafe_Solo('C', "Moka", 21);
        capuccino_frio = new Cafe_Solo('F', "Capuccino Frio", 30);
        moka_frio = new Cafe_Solo('F', "Moka Frio", 35);

        ls.add(capuccino);
        ls.add(americano);
        ls.add(express);
        ls.add(moka);
        ls.add(capuccino_frio);
        ls.add(moka_frio);

    }

    public void combo(DefaultComboBoxModel modelo) {
        cbxCafesBase.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Tipo = new javax.swing.ButtonGroup();
        pago = new javax.swing.ButtonGroup();
        radCaliente = new javax.swing.JRadioButton();
        radFrio = new javax.swing.JRadioButton();
        cbxCafesBase = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        panel = new javax.swing.JPanel();
        btnCajeta = new javax.swing.JButton();
        btnPanna = new javax.swing.JButton();
        btnOreo = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        radEfectivo = new javax.swing.JRadioButton();
        radTarjeta = new javax.swing.JRadioButton();
        btnAcepta = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtTotalPagar = new javax.swing.JTextField();
        etiNumIns = new javax.swing.JLabel();
        btnLimpia = new javax.swing.JButton();
        btnCrear = new javax.swing.JButton();
        etiIngredientes = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        etiPrecio_Decorado = new javax.swing.JLabel();

        setTitle("Arma tu cafe");

        Tipo.add(radCaliente);
        radCaliente.setSelected(true);
        radCaliente.setText("Caliente");
        radCaliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radCalienteActionPerformed(evt);
            }
        });

        Tipo.add(radFrio);
        radFrio.setText("Frio");
        radFrio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radFrioActionPerformed(evt);
            }
        });

        cbxCafesBase.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxCafesBase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxCafesBaseActionPerformed(evt);
            }
        });

        jLabel1.setText("Seleccione Cafe Base");

        panel.setLayout(new java.awt.GridLayout(1, 0));

        btnCajeta.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCajeta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/cajeta.jpg"))); // NOI18N
        btnCajeta.setText("Cajeta");
        btnCajeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCajetaActionPerformed(evt);
            }
        });
        panel.add(btnCajeta);

        btnPanna.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/panna.png"))); // NOI18N
        btnPanna.setText("Panna");
        btnPanna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPannaActionPerformed(evt);
            }
        });
        panel.add(btnPanna);

        btnOreo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/oreo.jpeg"))); // NOI18N
        btnOreo.setText("Oreo");
        btnOreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOreoActionPerformed(evt);
            }
        });
        panel.add(btnOreo);

        jLabel3.setText("Cantidad: ");

        txtCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCantidadKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCantidadKeyTyped(evt);
            }
        });

        pago.add(radEfectivo);
        radEfectivo.setSelected(true);
        radEfectivo.setText("Efectivo");

        pago.add(radTarjeta);
        radTarjeta.setText("Tarjeta");

        btnAcepta.setText("Aceptar");
        btnAcepta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptaActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel4.setText("Total a Pagar: ");

        txtTotalPagar.setEnabled(false);

        etiNumIns.setText("jLabel3");

        btnLimpia.setText("Restaurar Cafe Base");
        btnLimpia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiaActionPerformed(evt);
            }
        });

        btnCrear.setText("Crear Cafe");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        etiIngredientes.setFont(new java.awt.Font("Tahoma", 3, 10)); // NOI18N
        etiIngredientes.setText("Ingredientes : ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel2.setText("Precio c/u:");

        etiPrecio_Decorado.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        etiPrecio_Decorado.setText("      ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radEfectivo)
                            .addComponent(btnAcepta))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCancelar)
                                .addGap(36, 36, 36)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(txtTotalPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(etiNumIns)
                                .addGap(20, 20, 20))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(radTarjeta)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(radCaliente)
                                .addGap(26, 26, 26)
                                .addComponent(radFrio))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(31, 31, 31)
                                .addComponent(cbxCafesBase, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCrear)
                        .addGap(109, 109, 109)
                        .addComponent(btnLimpia)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(etiIngredientes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(etiPrecio_Decorado)
                        .addGap(2, 2, 2))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(radCaliente)
                            .addComponent(radFrio))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbxCafesBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(63, 63, 63))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCrear)
                            .addComponent(btnLimpia))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(radEfectivo)
                        .addComponent(radTarjeta))
                    .addComponent(etiIngredientes)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(etiPrecio_Decorado)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnAcepta)
                    .addComponent(etiNumIns)
                    .addComponent(jLabel4)
                    .addComponent(txtTotalPagar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptaActionPerformed
        costo_decorado = costo_decorado * obtenCantidad();
        if (radEfectivo.isSelected()) {
            Efectivo ce = new Efectivo(costo_decorado);
            ce.mostrar_pago();
        } else {
            Tarjetas ct = new Tarjetas(costo_decorado);
            ct.mostrar_pago();
        }
        // DESTRUYE SINGLETON
        Main.areaInforme.setText(null);
        Main.abierta_cc = false;
        this.instancia.dispose();
        this.instancia = null;
    }//GEN-LAST:event_btnAceptaActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // DESTRUYE SINGLETON
        Main.areaInforme.setText(null);
        Main.abierta_cc = false;
        this.instancia.dispose();
        this.instancia = null;
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void radFrioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radFrioActionPerformed
        iniciar('F');
    }//GEN-LAST:event_radFrioActionPerformed

    private void radCalienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radCalienteActionPerformed
        iniciar('C');
    }//GEN-LAST:event_radCalienteActionPerformed

    private void btnCajetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCajetaActionPerformed
        cajeta = true;
        btnCajeta.setEnabled(false);
    }//GEN-LAST:event_btnCajetaActionPerformed

    private void btnPannaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPannaActionPerformed
        panna = true;
        btnPanna.setEnabled(false);
    }//GEN-LAST:event_btnPannaActionPerformed

    private void btnOreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOreoActionPerformed
        oreo = true;
        btnOreo.setEnabled(false);
    }//GEN-LAST:event_btnOreoActionPerformed

    private void cbxCafesBaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxCafesBaseActionPerformed
        // Se establece el cafe elegido pibe
        if (radCaliente.isSelected()) {
            reinicia('C');
        } else {
            reinicia('F');
        }

        String nombre_cafe = cbxCafesBase.getSelectedItem().toString(); // Obtengo el cafe base
        base = ls.get_elegido(nombre_cafe, itt);
    }//GEN-LAST:event_cbxCafesBaseActionPerformed

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        // Este boton crearar los cafes con todos los ingredientes extras seleccionados
        // Existen 7 combinaciones posibles creo xD
        // Cafes con un ingrediente extra

         ingredientes = "Ingredientes : ";

        if (oreo == true && cajeta == false && panna == false) {
            Cafe cafe_o = new Oreo(base);
            ingredientes += cafe_o.ingredientes();
            costo_decorado = cafe_o.precio();
        }
        if (panna == true && oreo == false && cajeta == false) {
            Cafe cafe_p = new Panna(base);
            System.out.println(cafe_p.ingredientes());
            ingredientes += cafe_p.ingredientes();
            costo_decorado = cafe_p.precio();
        }
        if (cajeta == true && panna == false && oreo == false) {
            Cafe cafe_caj = new Cajeta(base);
            System.out.println(cafe_caj.ingredientes());
            ingredientes += cafe_caj.ingredientes();
            costo_decorado = cafe_caj.precio();
        }
        // Cafe con todos los ingredientes extras
        if (oreo == true && cajeta == true && panna == true) {
            Cafe cafe_todos = new Oreo(new Cajeta(new Panna(base)));
            System.out.println(cafe_todos.ingredientes());
            ingredientes += cafe_todos.ingredientes();
            costo_decorado = cafe_todos.precio();
        }
        // Cafe con oreo y cajeta
        if (oreo == true && cajeta == true && panna == false) {
            Cafe cafe_oc = new Oreo(new Cajeta(base));
            ingredientes += cafe_oc.ingredientes();
            costo_decorado = cafe_oc.precio();
        }
        // Cafe con oreo y panna
        if (oreo == true && panna == true && cajeta == false) {
            Cafe cafe_op = new Oreo(new Panna(base));
            ingredientes += cafe_op.ingredientes();
            costo_decorado = cafe_op.precio();
        }
        // Cafe con cajeta y panna
        if (cajeta == true && panna == true && oreo == false) {
            Cafe cafe_cp = new Cajeta(new Panna(base));
            ingredientes += cafe_cp.ingredientes();
            costo_decorado = cafe_cp.precio();
        }

        // Cafe sin nada pff
        if (cajeta == false && panna == false && oreo == false) {
            Cafe cafe_solo = base;
            ingredientes += cafe_solo.ingredientes();
            costo_decorado = cafe_solo.precio();
        }

        etiIngredientes.setText(ingredientes);
        etiPrecio_Decorado.setText("$ " + costo_decorado);
        txtTotalPagar.setText("$ " + costo_decorado * obtenCantidad());
        total_pagar = costo_decorado * obtenCantidad();

        cambiosMedicion();

    }//GEN-LAST:event_btnCrearActionPerformed

    private void btnLimpiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiaActionPerformed
        oreo = false;
        cajeta = false;
        panna = false;

        btnCajeta.setEnabled(true);
        btnOreo.setEnabled(true);
        btnPanna.setEnabled(true);
        etiIngredientes.setText(base.ingredientes());
        etiPrecio_Decorado.setText("$ " + base.getPrecio());
        costo_decorado = base.getPrecio();
        txtTotalPagar.setText("$ " + costo_decorado * obtenCantidad());
        total_pagar = costo_decorado * obtenCantidad();
        cambiosMedicion();
    }//GEN-LAST:event_btnLimpiaActionPerformed

    private void txtCantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadKeyTyped
        char c = evt.getKeyChar();
        if (Character.isLetter(c)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Ingresa numeros", "Tipo de dato erroneo", JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_txtCantidadKeyTyped

    private void txtCantidadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadKeyReleased
           etiPrecio_Decorado.setText("$ " + costo_decorado);
        txtTotalPagar.setText("$ " + costo_decorado * obtenCantidad());
        total_pagar = costo_decorado * obtenCantidad();
        
        cambiosMedicion();
        
    }//GEN-LAST:event_txtCantidadKeyReleased

    private int obtenCantidad() {
        int cantidad = 0;
        if (!txtCantidad.getText().isEmpty()) {
            cantidad = Integer.parseInt(txtCantidad.getText());
        } else {
            JOptionPane.showMessageDialog(rootPane, "Ingrese Cantidad de cafee a comprar");
        }
        return cantidad;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Tipo;
    private javax.swing.JButton btnAcepta;
    private javax.swing.JButton btnCajeta;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnLimpia;
    private javax.swing.JButton btnOreo;
    private javax.swing.JButton btnPanna;
    private javax.swing.JComboBox cbxCafesBase;
    private javax.swing.JLabel etiIngredientes;
    public static javax.swing.JLabel etiNumIns;
    private javax.swing.JLabel etiPrecio_Decorado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.ButtonGroup pago;
    private javax.swing.JPanel panel;
    private javax.swing.JRadioButton radCaliente;
    private javax.swing.JRadioButton radEfectivo;
    private javax.swing.JRadioButton radFrio;
    private javax.swing.JRadioButton radTarjeta;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtTotalPagar;
    // End of variables declaration//GEN-END:variables

    @Override
    public void remueveObservador(Observador o) {
        int i = observadores.indexOf(o);
        if (i >= 0) {
            observadores.remove(o);
        }
    }

    @Override
    public void notificaObservadores() {
        for (int i = 0; i < observadores.size(); i++) {
            Observador observador = (Observador) observadores.get(i);
            //(float costo_total,float costo_unitario,int cantidad, String nombre);
            observador.actualiza(total_pagar, costo_decorado, obtenCantidad(), etiIngredientes.getText());
        }
    }

    @Override
    public void registraObservador(Observador o) {
        observadores.add(o);
    }

    public void cambiosMedicion() {
        notificaObservadores(); /// cambio de estado modificacion en el estado
    }
}
